### ISSUE TITLE
Cannot find module `.cache/quasar-app-extension-ssg/server/server-entry.js`

### ISSUE THREAD

**Issue by renyuneyun** [freddy38510/quasar-app-extension-ssg#374]
After adding this extension, and try to build static site using `quasar ssg generate` (through `npm run build:ssg` which is automatically added), I receive the following error after building the pages:

```
 App •  DONE  • SSR Client compiled with success • 8644ms

 App •  WAIT  • Compiling of SSR Server with Vite in progress...
polyfillModulePreload is deprecated. Use modulePreload.polyfill instead.
Setting server.middlewareMode to 'ssr' is deprecated, set server.middlewareMode to `true` and appType to 'custom' instead
 App •  DONE  • SSR Server compiled with success • 1358ms

node:internal/modules/cjs/loader:1144
  const err = new Error(message);
              ^

Error: Cannot find module '/home/ryey/coding/solid-fixer/node_modules/.cache/quasar-app-extension-ssg/server/server-entry.js'
Require stack:
- /home/ryey/coding/solid-fixer/node_modules/quasar-app-extension-ssg/src/vite/ssg-create-render-fn.js
- /home/ryey/coding/solid-fixer/node_modules/quasar-app-extension-ssg/src/vite/ssg-builder.js
- /home/ryey/coding/solid-fixer/node_modules/quasar-app-extension-ssg/src/vite/cmd/generate.js
- /home/ryey/coding/solid-fixer/node_modules/quasar-app-extension-ssg/src/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at createRenderFn (/home/ryey/coding/solid-fixer/node_modules/quasar-app-extension-ssg/src/vite/ssg-create-render-fn.js:27:7)
    at SsgBuilder.generatePages (/home/ryey/coding/solid-fixer/node_modules/quasar-app-extension-ssg/src/vite/ssg-builder.js:83:64)
    at run (/home/ryey/coding/solid-fixer/node_modules/quasar-app-extension-ssg/src/vite/cmd/generate.js:119:20) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/ryey/coding/solid-fixer/node_modules/quasar-app-extension-ssg/src/vite/ssg-create-render-fn.js',
    '/home/ryey/coding/solid-fixer/node_modules/quasar-app-extension-ssg/src/vite/ssg-builder.js',
    '/home/ryey/coding/solid-fixer/node_modules/quasar-app-extension-ssg/src/vite/cmd/generate.js',
    '/home/ryey/coding/solid-fixer/node_modules/quasar-app-extension-ssg/src/index.js'
  ]
}

Node.js v21.2.0
```

I saw #332, but presume that is fixed and I shouldn't be expecting that error?
I'm using Vite 4, which is manually upgraded as Quasar itself doesn't use Vite 4, but I need it as the default version causes issues.

**Comment by freddy38510** [comment]
The fix is available in quasar-app-extension-ssg@5.1.1

I tested it by adding ` "resolutions": {
    "vite": "^4.0.0",
    "@vitejs/plugin-vue": "^4.0.0"
  }` to the package.json file.

Please note that this fix does not add support for vite v5.

**Comment by renyuneyun** [comment]
Thanks. I can confirm this issue has been fixed.

But unfortunately again there is another error... Will open a separate issue.
